name: CICD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Client-Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rajashekar1/devops-pipeline
          tags: client
          registry: docker.io
          dockerfile: ./client/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  Server-Build-and-Deploy:
    runs-on: ubuntu-latest
    needs: Client-Build-and-Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> ./server/.env
          echo "MONGODB_URI=${{ secrets.MONGO_URI }}" >> ./server/.env
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rajashekar1/devops-pipeline
          tags: server
          registry: docker.io
          dockerfile: ./server/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}.
          to: rajshekar9230@gmail.com
          from: amazonkosam221@gmail.com
